name: Sync Leetcode Submissions

on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync Leetcode Submissions
      uses: joshcai/leetcode-sync@v1.7
      with:
        github-token: ${{ github.token }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
        verbose: false
